/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RandomPotionImport } from './routes/random-potion'
import { Route as IngredientsImport } from './routes/ingredients'
import { Route as CreatePotionImport } from './routes/create-potion'
import { Route as IndexImport } from './routes/index'
import { Route as PotionPotionIdImport } from './routes/potion.$potionId'

// Create/Update Routes

const RandomPotionRoute = RandomPotionImport.update({
  path: '/random-potion',
  getParentRoute: () => rootRoute,
} as any)

const IngredientsRoute = IngredientsImport.update({
  path: '/ingredients',
  getParentRoute: () => rootRoute,
} as any)

const CreatePotionRoute = CreatePotionImport.update({
  path: '/create-potion',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PotionPotionIdRoute = PotionPotionIdImport.update({
  path: '/potion/$potionId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/create-potion': {
      id: '/create-potion'
      path: '/create-potion'
      fullPath: '/create-potion'
      preLoaderRoute: typeof CreatePotionImport
      parentRoute: typeof rootRoute
    }
    '/ingredients': {
      id: '/ingredients'
      path: '/ingredients'
      fullPath: '/ingredients'
      preLoaderRoute: typeof IngredientsImport
      parentRoute: typeof rootRoute
    }
    '/random-potion': {
      id: '/random-potion'
      path: '/random-potion'
      fullPath: '/random-potion'
      preLoaderRoute: typeof RandomPotionImport
      parentRoute: typeof rootRoute
    }
    '/potion/$potionId': {
      id: '/potion/$potionId'
      path: '/potion/$potionId'
      fullPath: '/potion/$potionId'
      preLoaderRoute: typeof PotionPotionIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  CreatePotionRoute,
  IngredientsRoute,
  RandomPotionRoute,
  PotionPotionIdRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/create-potion",
        "/ingredients",
        "/random-potion",
        "/potion/$potionId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/create-potion": {
      "filePath": "create-potion.tsx"
    },
    "/ingredients": {
      "filePath": "ingredients.tsx"
    },
    "/random-potion": {
      "filePath": "random-potion.tsx"
    },
    "/potion/$potionId": {
      "filePath": "potion.$potionId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
