/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PotionPotionIdImport } from './routes/potion.$potionId'

// Create Virtual Routes

const IngredientsLazyImport = createFileRoute('/ingredients')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IngredientsLazyRoute = IngredientsLazyImport.update({
  path: '/ingredients',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/ingredients.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const PotionPotionIdRoute = PotionPotionIdImport.update({
  path: '/potion/$potionId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/ingredients': {
      id: '/ingredients'
      path: '/ingredients'
      fullPath: '/ingredients'
      preLoaderRoute: typeof IngredientsLazyImport
      parentRoute: typeof rootRoute
    }
    '/potion/$potionId': {
      id: '/potion/$potionId'
      path: '/potion/$potionId'
      fullPath: '/potion/$potionId'
      preLoaderRoute: typeof PotionPotionIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  IngredientsLazyRoute,
  PotionPotionIdRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/ingredients",
        "/potion/$potionId"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/ingredients": {
      "filePath": "ingredients.lazy.tsx"
    },
    "/potion/$potionId": {
      "filePath": "potion.$potionId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
